# Generated by Django 6.0.5 on 2026-07-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_replyvote'),
        ('game', '0031_activegame_game_active_status_22ef23_idx'),
    ]

    operations = [
    ]
